### ISSUE TITLE
Repeated "error loading dynamically imported module"

### ISSUE THREAD

**Issue by Taurus-II** [makzu/lotcastingatemi#159]
I am getting repeated instances of this error

When I try to open the Characters list: "error loading dynamically imported module: https://www.lotcastingatemi.com/vite/assets/index-Dw5_oMh9.js"

If I open the url in a new tab, I can get to the lists of Quick Characters and Battlegroups; however, attempting to open any particular QC gives "error loading dynamically imported module: https://www.lotcastingatemi.com/vite/assets/index-COxJkulE.js", and any particular Battlegroup "error loading dynamically imported module: https://www.lotcastingatemi.com/vite/assets/index-DpPTtMJN.js"

Help: "error loading dynamically imported module: https://www.lotcastingatemi.com/vite/assets/Help-BmAo3IQE.js"

Resources: "error loading dynamically imported module: https://www.lotcastingatemi.com/vite/assets/ResourcesPage-D-I7A-VT.js"

**Comment by makzu** [comment]
Which browser are you seeing these error messages in? And which version of that browser? (You can usually find that info in the menu under Help > About [Browser])

**Comment by Taurus-II** [comment]
Sorry, Firefox 131.0.2 (64-bit)

**Comment by Taurus-II** [comment]
The error is persisting on desktop even though I'm now on 131.0.3 — however it works fine when I use Firefox on my Android tablet. I have my adblocker turned off, I have both whitelisted the site _and_ tried to load it with my scriptblocker disabled (even though I have the same addons installed on the mobile version, which accesses things fine).

Opening up the Firefox console, I see these errors:
```
TypeError: Document.getElementsByTagName is not a function[gnu.js:2:22](moz-extension://7bc7f6e5-8c71-4a00-9998-be105b0d71d6/gnu.js)
    <anonymous> moz-extension://7bc7f6e5-8c71-4a00-9998-be105b0d71d6/gnu.js:2
    #injectIntoIsolatedWorld resource://gre/modules/ExtensionContent.sys.mjs:678
    inject resource://gre/modules/ExtensionContent.sys.mjs:663
    injectInto resource://gre/modules/ExtensionContent.sys.mjs:534
    AsyncFunctionNext self-hosted:807
TypeError: error loading dynamically imported module: https://www.lotcastingatemi.com/vite/assets/Help-BmAo3IQE.js [react-dom.production.min.js:209:194](https://www.lotcastingatemi.com/node_modules/react-dom/cjs/react-dom.production.min.js)
    React 5
        ec
        callback
        Rp
        Rx
        Nx
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
        ir
        fr
        oc
        ug
    unstable_runWithPriority scheduler.production.min.js:19
    React 2
        ir
        ug
    q scheduler.production.min.js:17
    onmessage scheduler.production.min.js:14
    (Async: EventHandlerNonNull)
    <anonymous> scheduler.production.min.js:13
    <anonymous> scheduler.production.min.js:21

**Comment by makzu** [comment]
I use that version of Firefox for my own development and testing and I can't reproduce the issue.

If you look at the network tab of the developer tools, does it show anything helpful while trying to load things like Help-xyz.js or ResourcesPage-xyz.js, for example? It does look like there's some kind of issue preventing the lazy loading from working.

**Comment by Taurus-II** [comment]
... well I don't know what originally caused the issue, but clearing out my cache fixed it. I probably should have tried that sooner.
