### ISSUE TITLE
QC fields misbehaving

### ISSUE THREAD

**Issue by Chaemera** [makzu/lotcastingatemi#3]
Attempting to fill in the Control field for Grapple doesn't work and resets the Grapple field to 1.

Also can't seem to delete a QC once created, clicking the Delete button does nothing, doesn't even close the popup.

**Comment by makzu** [comment]
Spotted the typo. This will be fixed in the next release.  Thanks for your report!

**Comment by makzu** [comment]
v43 is live and should fix the issue.

**Comment by Chaemera** [comment]
Except now both Dodge and Parry are both reading from the Dodge field.

**Comment by makzu** [comment]
Yep, that issue was resolved in 45a99ef, which will be in v44.
