### ISSUE TITLE
Can't remove attacks from quick characters.

### ISSUE THREAD

**Issue by ChrisWellsWood** [makzu/lotcastingatemi#5]
You can't remove attacks from quick characters after they've been added.

Loving Lot-Casting Atemi btw! I have a bunch of web development experience (although not in React or Ruby, day to day I use Elm and Python) so I was thinking that I could help contribute in the future. Keep up the good work!

**Comment by makzu** [comment]
This might be related to an issue others are having with weapons and Charms.  After reloading the page, is the attack in question gone?

**Comment by ChrisWellsWood** [comment]
Yes it is. It seems to be working properly now, not sure what caused it. If I can reproduce it I'll reopen the issue.

**Comment by makzu** [comment]
I overhauled the code that handles deleting things in v49, so hopefully this won't be an issue any longer. Thanks for your feedback!
