### ISSUE TITLE
Excellency limit incorrect of QC

### ISSUE THREAD

**Issue by lurtze1** [makzu/lotcastingatemi#65]
The excellency limits suggestions from the dragon-blooded qc characters do not match what the book says. Core Page 541 for the QC static value limit list
![unknown](https://user-images.githubusercontent.com/9928487/190506499-226bf3ef-9c29-4348-9efa-59e0bd9925a9.png)
![2](https://user-images.githubusercontent.com/9928487/190506522-3a6e4cd7-eac6-46d1-8129-5fbd204816f6.png)

**Comment by makzu** [comment]
Fixed by #67
