### ISSUE TITLE
No option to change character type after creation

### ISSUE THREAD

**Issue by DunkUK** [makzu/lotcastingatemi#7]
I have a mortal character that became exulted, and it would be handy if I could either change the character sheet from one mode to the other or have a way to clone an existing character when making a new one.
Right now I have to create the character again from scratch and manually copy the fields.
With hindsight, I probably should've just created the char as exulted from the start and assumed the storyteller would go there :o)

**Comment by makzu** [comment]
As of v64 you can now change from any exalt type to any other exalt type, including mortals.
