### ISSUE TITLE
No option to drop caste abilities

### ISSUE THREAD

**Issue by DylanReedy** [makzu/lotcastingatemi#8]
Once a caste ability is chosen, there doesn't seem to be a way to drop that ability for another one.

**Comment by makzu** [comment]
You should be able to remove Caste Abilities from the list by clicking them again in the menu.

Supernal Abilities can't be removed from the Caste Ability list for canon Solars, so to remove that you'll want to change your Supernal first or switch to another Caste to clear the list.  Custom Ability Exalts don't have that restriction.

**Comment by DylanReedy** [comment]
Ahh - I was MA supernal and was trying to remove Brawl! Not exactly the Supernal, but a pre-requisite. Nice code detail.
