### ISSUE TITLE
Chronicle Notes Field Keeps Injecting Duplicate Data

### ISSUE THREAD

**Issue by claycle** [makzu/lotcastingatemi#88]
On the Chronicle page, when attempting to make any change to the Chronicle Notes field, when the field loses focus the previous data in the field is append to the new data in the field with a comma.

For example:

I enter a note for the chronicle:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/419840/213822911-07dab960-57b6-4319-9b86-a43108c49fe3.png">

I then conclude that I do not like the word "first". I want to change it to "primary", so I edit the field again:

<img width="227" alt="image" src="https://user-images.githubusercontent.com/419840/213822980-c35e1860-e502-4b7a-919f-c6facc726dbc.png">

When I leave the field, the following occurs:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/419840/213823027-79fbc8c8-2d65-4b53-8fd1-2c34226f7396.png">

Thinking I have made some error, I try to edit the field again:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/419840/213823079-c15b1b4a-81bb-46e3-823a-34462834058b.png">

In fact, every time I leave the window, the field gets longer and longer:

<img width="900" alt="image" src="https://user-images.githubusercontent.com/419840/213823119-64b150e2-5e3b-44f9-a2e2-ac7ef4fef34d.png">

In fact, deleting all the information in the field (select all, delete key) produces the following result when focus is lost:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/419840/213823181-7905745e-f10f-4bc1-ab14-462971461d8d.png">

Duplicated in Firefox and Safari.

**Comment by makzu** [comment]
Confirmed. Thanks for your very detailed report!

**Comment by makzu** [comment]
This should be fixed in the newly released v96. Thanks again for reporting!
